name: general-rag

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: general-rag-backend
    restart: always
    ports:
      - "1002:1002"
    env_file:
      - ./backend/.env
    environment:
      - ENVIRONMENT=production
      - CORS_ORIGINS=["https://cognava.calvinandrean.web.id","http://localhost:1001","http://127.0.0.1:1001","http://localhost:3000","http://localhost:1002","http://127.0.0.1:1002"]
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_API_URL: /api/v1
    container_name: general-rag-frontend
    restart: always
    ports:
      - "1001:80"
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
